### ISSUE TITLE
Mod dont start i have logs

### ISSUE THREAD

**Issue by FofanV5** [oldnapalm/GTACoop#10]
[22:27:49] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[22:27:49] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[22:27:49] [DEBUG] Loading scripts from C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts ...
[22:27:49] [DEBUG] Loading assembly GTACoOp.dll ...
[22:27:49] [INFO] Found 2 script(s) in GTACoOp.dll resolved to API 3.6.0.
[22:27:49] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[22:27:49] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[22:27:49] [DEBUG] Loading assembly Lidgren.Network.MultiTarget.dll ...
[22:27:49] [INFO] Found 0 script(s) in Lidgren.Network.MultiTarget.dll.
[22:27:49] [DEBUG] Loading assembly MaxMind.Db.dll ...
[22:27:49] [INFO] Found 0 script(s) in MaxMind.Db.dll.
[22:27:49] [DEBUG] Loading assembly MaxMind.GeoIP2.dll ...
[22:27:49] [INFO] Found 0 script(s) in MaxMind.GeoIP2.dll.
[22:27:49] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[22:27:49] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[22:27:49] [DEBUG] Loading assembly protobuf-net.dll ...
[22:27:49] [INFO] Found 0 script(s) in protobuf-net.dll.
[22:27:49] [DEBUG] Instantiating script GTACoOp.Main ...
[22:27:50] [ERROR] Failed to instantiate script GTACoOp.Main because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.get_CellEmailBcon()
   at GTA.UI.Notification.Show(String message, Boolean blinking)
   at GTACoOp.Main..ctor()
[22:27:50] [DEBUG] Instantiating script GTACoOp.PedThread ...
[22:27:50] [INFO] Started script GTACoOp.PedThread.

**Comment by oldnapalm** [comment]
This is a ScriptHookVDotNet issue, for GTA version 1.0.3258 or later you need to use the nightly build

https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases
